version: '3.8'
services:
  aeps-db:
    image: postgres:15
    container_name: rupay_postgres_container
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
      POSTGRES_DB: rupay_transactions
    ports:
      - "5432:5432"  # <--- MUST BE 5433:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: rupay_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data: